#!/bin/zsh

name=$1

function latestVersionOfPackage () {
    cabal info "$1" \
    | grep -Pzo 'Versions available:(.|\n)*?:' \
    | head -n-1 \
    | tail -n1 \
    | sed -r 's/.*? ([0-9.]+)\s*(\(and [0-9]+ others\))?\s*?/\1/'
}

function addDepToCabalFile () {
    sed -i.bak -r 's/(\s*)(build-depends:)(\s+)(.*?)$/\1\2\3'"$1"',\n\1              \3\4/ig' *.cabal
}
latestVersion=$(latestVersionOfPackage $name)

echo Latest version found: $latestVersion

addDepToCabalFile "$name ==$latestVersion"

cabal install --only-dependencies